#! /bin/sh

### BEGIN INIT INFO
# Provides:          resque
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts rake task
# Description:       starts rake task
### END INIT INFO

NAME=resque
RAILS_ENV=production
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
APP_PATH=/opt/rails/kuzi
DAEMON=/usr/local/bin/rake
DAEMON_OPTS='resque:work QUEUE=*'

case "$1" in
  start)
    cd $APP_PATH && RAILS_ENV=$RAILS_ENV $DAEMON $DAEMON_OPTS > /dev/null 2>&1 &
  ;;

  stop)
    pkill -9 rake
  ;;

  restart)
    pkill -9 rake
    cd $APP_PATH && RAILS_ENV=$RAILS_ENV $DAEMON $DAEMON_OPTS > /dev/null 2>&1 &
  ;;

  *)
	echo "Parameters: start|stop|restart"
  ;;
esac

exit 0
