source 'http://rubygems.org'
#ruby '1.9.2'
gem 'rails', '3.2.12'

if RUBY_VERSION =~ /1.9/
  Encoding.default_external = Encoding::UTF_8
  Encoding.default_internal = Encoding::UTF_8
end

# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'

gem 'mysql2', "0.3.10"
gem 'jquery-rails', "1.0.15"
gem "babosa", "0.3.5"
#gem "friendly_id", "3.3.0.1"
gem 'friendly_id', '~> 4.0.9'
gem "state_machine"
gem 'resque', "1.19.0", :require => "resque/server"
gem 'resque-status', "0.2.4"
gem 'resque-ensure-connected'

gem 'client_side_validations', "3.1.0"

gem 'to_xls', "1.0.0"
gem 'spreadsheet', "0.6.5.9"
gem 'dalli', "1.1.2"
gem 'tinymce-rails', "3.5.2"

gem 'kaminari', "0.13.0"
gem 'carrierwave', "0.5.7"
gem 'rmagick', "2.13.1"
gem 'mini_magick'
gem 'cloudinary'

gem 'meta_search', "1.1.3"

gem 'unicode_utils', "1.0.0"

gem 'cancan', "1.6.7"

gem 'simple_form', "1.5.2"
gem 'simple-navigation', "3.5.0"

gem 'redcarpet', "1.17.2"

gem 'prawn'

gem 'activemerchant', :require => 'active_merchant'

gem 'bcrypt-ruby', '~> 3.0.0'

gem 'rubyzip'

# Asset template engines
group :assets do
  gem 'json', "1.7.3"
  gem 'sass', "3.1.19"
  gem 'sass-rails', "3.2.5"
  gem 'compass-rails'#,'~> 1.0.0.rc.2'
  #gem 'compass', "~> 0.12.alpha.0"
  gem 'compass-susy-plugin', "0.9"
  gem 'coffee-script', "2.2.0"
  gem 'uglifier', ">= 1.0.3"
  # gem "handlebars-rails"
  #gem 'therubyracer', "0.9.8"
  gem 'libv8', '~> 3.11.8'
  gem "therubyracer", '>= 0.11.0beta1', :require => 'v8'
end

group :development do
  gem 'pry-rails'
  gem 'thin'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'meta_request'
  gem 'zeus', ">= 0.13.4.pre2"
  gem 'jazz_hands'
end
group :test do
#  gem 'database_cleaner', "~> 0.8.0"
#  gem 'rails3-generators',"0.17.4"
#  gem 'rspec-rails', "~> 2.11.0"
#  gem 'shoulda-matchers', "~> 1.3.0"
#  gem 'factory_girl_rails', "~> 3.5.0"
#  gem 'cucumber-rails', "~> 1.3.0"
#  gem 'turn', "0.8.3", :require => false
#  gem 'capybara', "~> 1.1.2"
end

#gem "eventmachine", :git => "https://github.com/eventmachine/eventmachine.git"
gem 'rubyzip', :require => 'zip/zip'
gem 'zip-zip'

gem 'slim'
gem 'slim-rails'

gem 'postmark-rails'
